#!/usr/bin/env python3
"""Build the self-contained Meltwater Discharge Explorer.

Reads the GLAC-1D and ICE-6G regional discharge series, the Glas stalagmite
d18O record, the approximate region outlines and the Natural Earth coastline,
and injects them as one JSON object into app/template.html.

Outputs
  app/discharge_explorer.html   full HTML document (open locally in a browser)
  --publish-out PATH            optional second copy without the document
                                wrapper, as the claude.ai Artifact format expects

Standard library only. Run from the repository root:
  python3 app/build_app.py [--publish-out PATH]
"""
import argparse
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
APP = ROOT / "app"

CODES = ["Med", "Bri", "Fen", "EurArc", "AmeArc", "GIS", "NLau", "SLau", "GulofMex"]
SHORT = {"GulofMex": "GoM"}
END_MEMBERS = ["-30", "-35", "-40"]

# Abrupt Glas d18O events, Endres et al. (2026a, Table 1): midpoint and 95 % CI (yr BP)
EVENTS = [
    ("23.4kS", 23440, 23330, 24050, 1),
    ("17.8kS", 17840, 17820, 18030, -1),
    ("16.4kS", 16440, 16140, 16550, -1),
    ("16.1kS", 16070, 15900, 16380, -1),
    ("15.3kS", 15270, 15140, 15360, -1),
    ("14.7kS", 14680, 14540, 14810, 1),
]


def rnd(x, sig=5):
    """Round to significant digits to keep the inlined JSON small."""
    return float(f"{x:.{sig}g}")


def read_rows(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def discharge(path, tcol, qprefix, step):
    rows = read_rows(path)
    rows.sort(key=lambda r: float(r[tcol]))                   # oldest first (model time is negative)
    out = {"step": step, "ages": [], "Q": {c: [] for c in CODES},
           "A": {e: {c: [] for c in CODES} for e in END_MEMBERS}}
    for r in rows:
        age = -float(r[tcol])                                  # model time -> yr BP
        if age < 0:                                            # drop steps after present
            continue
        out["ages"].append(round(age))
        for c in CODES:
            out["Q"][c].append(rnd(float(r[qprefix + c])))
            for e in END_MEMBERS:
                out["A"][e][c].append(rnd(float(r[f"{c} d18O ({float(e):.1f})"])))
    return out


def glas_record():
    entity = next(r for r in read_rows(DATA / "entity.csv") if r["entity_name"] == "Glas")
    ids = {r["sample_id"] for r in read_rows(DATA / "sample.csv") if r["entity_id"] == entity["entity_id"]}
    age = {r["sample_id"]: float(r["interp_age"]) for r in read_rows(DATA / "original_chronology.csv") if r["sample_id"] in ids}
    d18o = {r["sample_id"]: float(r["d18O_measurement"]) for r in read_rows(DATA / "d18O.csv") if r["sample_id"] in ids}
    pts = sorted((age[s], d18o[s]) for s in ids if s in age and s in d18o)
    return {"age": [round(a) for a, _ in pts], "d18o": [round(d, 2) for _, d in pts]}


def build():
    geo = json.loads((APP / "regions_approx.geojson").read_text(encoding="utf-8"))
    props = {f["properties"]["code"]: f["properties"] for f in geo["features"]}
    regions = [{
        "code": c, "short": SHORT.get(c, c),
        "name_draft": props[c]["name_draft"], "name_2026b": props[c]["name_2026b"],
        "ice_sheet": props[c]["ice_sheet"], "drainage": props[c]["drainage"],
    } for c in CODES]
    payload = {
        "regions": regions,
        "recon": {
            "GLAC-1D": discharge(DATA / "Discharge_Glac1d_regional-withd18O.csv", "time", "", 100),
            "ICE-6G": discharge(DATA / "Discharge_ice6g_regional-withd18O.csv", "t_adj", "discharge_", 500),
        },
        "glas": glas_record(),
        "events": [dict(zip(["event", "mid", "lo", "hi", "sign"], e)) for e in EVENTS],
        "geo": {"type": "FeatureCollection", "features": geo["features"]},
        "sites": geo["metadata"]["sites"],
        "land": json.loads((APP / "vendor" / "land-110m.json").read_text(encoding="utf-8")),
    }
    return payload


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--publish-out", type=Path, help="also write the Artifact copy (no document wrapper) here")
    args = ap.parse_args()

    payload = build()
    blob = json.dumps(payload, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")
    template = (APP / "template.html").read_text(encoding="utf-8")
    assert template.count("/*__DATA__*/null") == 1, "data placeholder missing"
    page = template.replace("/*__DATA__*/null", blob)
    head, body = page.split("<!--HEAD-END-->", 1)

    full = ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
            "<!-- Generated by app/build_app.py from app/template.html; do not edit by hand. -->\n"
            + head.strip() + "\n</head>\n<body>\n" + body.strip() + "\n</body>\n</html>\n")
    out = APP / "discharge_explorer.html"
    out.write_text(full, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size / 1024:.0f} KB)")

    if args.publish_out:
        args.publish_out.write_text(head.strip() + "\n" + body.strip() + "\n", encoding="utf-8")
        print(f"wrote {args.publish_out} ({args.publish_out.stat().st_size / 1024:.0f} KB)")

    # Spot checks for the verification checklist
    for name, r in payload["recon"].items():
        tot = [sum(r["Q"][c][i] for c in CODES) for i in range(len(r["ages"]))]
        i = max(range(len(tot)), key=tot.__getitem__)
        print(f"{name}: {len(r['ages'])} steps, {r['ages'][0]}-{r['ages'][-1]} yr BP, "
              f"peak total {tot[i]:.3f} Sv at {r['ages'][i] / 1000:.1f} ka")


if __name__ == "__main__":
    main()
